import {
  Archive,
  BarChart3,
  BookOpen,
  Building2,
  ClipboardList,
  FileText,
  HandCoins,
  Package,
  Receipt,
  Users,
  Wallet,
} from 'lucide-react';

export const staffModules = [
  {
    slug: 'membership',
    title: 'Membership',
    description: 'Member onboarding, profiles, approvals, and status reviews.',
    icon: Users,
    color: 'blue',
    metric: '1,284',
    metricLabel: 'active members',
    queues: ['Pending applications', 'KYC reviews', 'Member updates'],
  },
  {
    slug: 'savings',
    title: 'Savings',
    description: 'Deposits, withdrawals, transfers, and member savings ledgers.',
    icon: Wallet,
    color: 'green',
    metric: 'KES 8.7M',
    metricLabel: 'total savings',
    queues: ['Deposit approvals', 'Withdrawal checks', 'Savings adjustments'],
  },
  {
    slug: 'loans',
    title: 'Loans',
    description: 'Loan applications, approvals, disbursements, and collections.',
    icon: HandCoins,
    color: 'purple',
    metric: '43',
    metricLabel: 'open cases',
    queues: ['New applications', 'Appraisal queue', 'Repayment follow-ups'],
  },
  {
    slug: 'payables',
    title: 'Payables',
    description: 'Supplier bills, payment approvals, and expense scheduling.',
    icon: Receipt,
    color: 'orange',
    metric: 'KES 420K',
    metricLabel: 'due this month',
    queues: ['Vendor bills', 'Payment runs', 'Expense approvals'],
  },
  {
    slug: 'receivables',
    title: 'Receivables',
    description: 'Invoices, expected receipts, arrears, and collection tracking.',
    icon: FileText,
    color: 'blue',
    metric: 'KES 615K',
    metricLabel: 'expected receipts',
    queues: ['Open invoices', 'Collections', 'Aging review'],
  },
  {
    slug: 'fixed-assets',
    title: 'Fixed Assets',
    description: 'Asset register, depreciation, custody, and disposal workflows.',
    icon: Building2,
    color: 'green',
    metric: '126',
    metricLabel: 'registered assets',
    queues: ['Asset additions', 'Depreciation run', 'Disposals'],
  },
  {
    slug: 'inventory',
    title: 'Inventory',
    description: 'Stock items, issue requests, reorder levels, and adjustments.',
    icon: Package,
    color: 'orange',
    metric: '18',
    metricLabel: 'low-stock items',
    queues: ['Stock requests', 'Goods received', 'Adjustments'],
  },
  {
    slug: 'chart-of-accounts',
    title: 'Chart of Accounts',
    description: 'Account codes, ledger groups, posting rules, and balances.',
    icon: BookOpen,
    color: 'purple',
    metric: '92',
    metricLabel: 'ledger accounts',
    queues: ['New account setup', 'Posting rules', 'Ledger review'],
  },
  {
    slug: 'reports',
    title: 'Reports',
    description: 'Operational, financial, member, savings, and loan reporting.',
    icon: BarChart3,
    color: 'blue',
    metric: '24',
    metricLabel: 'saved reports',
    queues: ['Monthly reports', 'Audit packs', 'Export requests'],
  },
];

export const staffShortcuts = [
  { label: 'Approvals', value: '31', icon: ClipboardList, color: 'blue' },
  { label: 'Payments Due', value: '12', icon: Receipt, color: 'orange' },
  { label: 'Stock Alerts', value: '18', icon: Archive, color: 'green' },
  { label: 'Reports Ready', value: '7', icon: BarChart3, color: 'purple' },
];
